site_name: Pitanguy
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
    accenty: green
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - blog
  